### ISSUE TITLE
Add label and show on mouse hover on element

### ISSUE THREAD

**Issue by NilsChudalla** [cgre-aachen/gemgis#117]
I love the simplicity to add large sets of different data. However, some points/lines/... are too much or you cannot find that one point in your raw data. 

Having an option to plot elements with a label, which is visible on mouse hover or click would make navigation more comfortable. (This is more of an pyvista issue, but it would improve the GIS aspect)

**Comment by AlexanderJuestel** [comment]
Totally agree on that. I try to put something together the next few days and get back to you

**Comment by AlexanderJuestel** [comment]
This could be interesting with respect to your issue

https://github.com/pyvista/pyvista/pull/362

**Comment by AlexanderJuestel** [comment]
So, there are the functions ``enable_point_picking`` and ``enable_line_picking`` which also allow callback functions which we then can use to display the necessary information you need

**Comment by AlexanderJuestel** [comment]
Just a little collection of functions in PyVista that may be useful to solve that

![image](https://user-images.githubusercontent.com/45469915/105496071-47510b00-5cbd-11eb-928a-cf8fc1f9c1e8.png)
![image](https://user-images.githubusercontent.com/45469915/105496112-546dfa00-5cbd-11eb-8ece-3eff89e2fd92.png)
![image](https://user-images.githubusercontent.com/45469915/105496127-5c2d9e80-5cbd-11eb-8ea1-f53fa4ee1f54.png)
![image](https://user-images.githubusercontent.com/45469915/105496154-62237f80-5cbd-11eb-8023-815a923302c6.png)
![image](https://user-images.githubusercontent.com/45469915/105496246-82ebd500-5cbd-11eb-8c92-4b8865e70cc8.png)
![image](https://user-images.githubusercontent.com/45469915/105496315-99922c00-5cbd-11eb-8f66-b86bb522689d.png)
![image](https://user-images.githubusercontent.com/45469915/105496365-ab73cf00-5cbd-11eb-9c68-9f2cd696ee56.png)
![image](https://user-images.githubusercontent.com/45469915/105496424-baf31800-5cbd-11eb-83c6-cf4737c42be1.png)

**Comment by AlexanderJuestel** [comment]
Issue will be closed for now
