### ISSUE TITLE
Add support for GeoDataFrames to GemPy

### ISSUE THREAD

**Issue by mtb-za** [cgre-aachen/gemgis#12]
GemPy currently works with pandas DataFrames. Geopandas is an extension to pandas which allows for spatial operations on data. This includes selection of data within a given area, checking whether one geometry contains another, intersections and so on.

To switch from a DataFrame to a geoDataFrame requires the addition of coordinates and a CRS. They can be added either automatically by importing a spatial file format (`.shp`, `.gpkg`) or by converting a given geometry column and assigning a CRS to the metadata. This will also create a spatial index which can be used to query the DataFrame based on location, in addition to other attributes.

In principle, this is a fairly simple change, and should in most cases be non-breaking, since all the normal methods for DataFrames are available to GeoDataFrames. The advantage will be in gaining the ability to query parts of a model spatially: one could subset an existing model's points by eastings and northings or similar.

In the absence of a geometry, GemPy should fall back on using a standard DataFrame as it already does.

**Comment by mtb-za** [comment]
This should close issues #4, #5 and #7.

**Comment by AlexanderJuestel** [comment]
We are currently creating a first stable version of GemGIS which will fully support GeoPandas :)
