### ISSUE TITLE
Shapely and pyGEOS versions conflicting by configuring Gemgis environment following the docs instructions

### ISSUE THREAD

**Issue by pvabreu7** [cgre-aachen/gemgis#144]
Hello there, this is the first issue I open here on github, so I hope I get it to make it clear and straightforward.

**Bug description**
Apparently, there is some conflict between shapely geos version and pygeos compiled geos version. I followed the documentation to install all the packages and tried changing both shapely and pygeos versions and it still didn't worked. Though, I've find a way to make gemgis work by commenting the code that raised the exception. I don't feel like this is the ideal workaround and I guess we could figure it out better for new users to configure their environments.

The raised excpetion looks like this:
```python
ImportError                               Traceback (most recent call last)
<ipython-input-9-5733fef52eb6> in <module>
      1 extent = gpd.read_file('../data/extent.geojson')
----> 2 extent = gg.utils.set_extent(gdf=extent, minz=100, maxz=900)
      3 
      4 # Creating a figure with two subplots
      5 fig, (ax1, ax2) = plt.subplots(ncols=2, sharex=True, sharey=True,figsize=(20,10))

~\anaconda3\envs\gemgis\lib\site-packages\gemgis\utils.py in set_extent(minx, maxx, miny, maxy, minz, maxz, gdf)
    325 
    326     # Create extent from gdf of geom_type polygon
--> 327     elif all(pygeos.get_type_id(pygeos.from_shapely(gdf.geometry)) == 2):
    328 
    329         # Checking if the gdf is of type GeoDataFrame

~\anaconda3\envs\gemgis\lib\site-packages\pygeos\io.py in from_shapely(geometry, **kwargs)
    229     # pygeos has something like: "3.6.2-CAPI-1.10.2"
    230     if not shapely_geos_version.startswith(geos_capi_version_string):
--> 231         raise ImportError(
    232             "The shapely GEOS version ({}) is incompatible with the GEOS "
    233             "version PyGEOS was compiled with ({})".format(

ImportError: The shapely GEOS version (3.9.0-CAPI-1.14.1) is incompatible with the GEOS version PyGEOS was compiled with (3.9.0-CAPI-1.16.2)
```
My workaroung was to comment this exception at io.py:
```python
    if shapely_geos_version is None:
        raise ImportError("This function requires shapely")

    # shapely has something like: "3.6.2-CAPI-1.10.2 4d2925d6"
    # pygeos has something like: "3.6.2-CAPI-1.10.2"
    #if not shapely_geos_version.startswith(geos_capi_version_string):
    #    raise ImportError(
    #        "The shapely GEOS version ({}) is incompatible with the GEOS "
    #        "version PyGEOS was compiled with ({})".format(
    #            shapely_geos_version, geos_capi_version_string
    #        )
    #    )
```

**To Reproduce**
I just followed the documentation:
1. Create a new conda environment with the required python version.
2. Install geospatial libraries (geopandas and rasterio) with conda-forge.
3. Install gemgis with git.
4. Install pygeos and the remaining required libraries with pip

**Comment by AlexanderJuestel** [comment]
Hey @pvabreu7,

Thanks for the issue! 

What worked for me the other day was to install pygeos first and then geopandas and rasterio, all via conda forge. So the order matters when installing the packages!

Try this and let us know if that workaround was helpful! We will soon add the advice to install pygeos first to the documentation as well.

Cheers Alex

PS: Good description of your issue. Keep it up!

**Comment by pvabreu7** [comment]
> Hey @pvabreu7,
> 
> Thanks for the issue!
> 
> What worked for me the other day was to install pygeos first and then geopandas and rasterio, all via conda forge. So the order matters when installing the packages!
> 
> Try this and let us know if that workaround was helpful! We will soon add the advice to install pygeos first to the documentation as well.
> 
> Cheers Alex
> 
> PS: Good description of your issue. Keep it up!

Hello Alexander, I followed your solution and here is how I made a new environment:

conda create -n fixgemgis python==3.8.5
conda install -c conda-forge jupyter
conda install -c conda-forge pygeos
conda install -c conda-forge geopandas rasterio
pip install gempy

Then I installed gemgis via git
When I tried to run a notebook from the tutorials, importing Geopandas raised an exception:

```python
~\anaconda3\envs\fixgemgis\lib\site-packages\rtree\finder.py in load()
     65             finally:
     66                 os.environ['PATH'] = oldenv
---> 67         raise OSError("could not find or load {}".format(lib_name))
     68 
     69     elif os.name == 'posix':

OSError: could not find or load spatialindex_c-64.dll
```

Then I've searched on stackoverflow and find that the solution was to [pip uninstall rtree](https://stackoverflow.com/questions/45901732/could-not-find-or-load-spatialindex-c-dll-in-windows/45970431).

Uninstalling rtree solved this error. Following the instalation instructions from the docs, I've pip installed all of the remaining dependencies:
pip install xmltodict
pip install scikit-learn
pip install geopy
pip install xarray
pip install mplstereonet
pip install OWSLib

**And it worked fine!**
Thanks for the solution, Alexander. I hope that it helped to support updates on the installation instructions on the documentation.

**Comment by AlexanderJuestel** [comment]
Hey @pvabreu7,

This rtree error pops up once in a while. I have now released a new version on PyPi and will check if everythings works. I also tried to remove most of the dependencies to make them optional. Let's see if that works. 

But we should have a workaround present for that on the documentation page for sure!
