### ISSUE TITLE
Generate GeoTiff from Geological Map

### ISSUE THREAD

**Issue by AlexanderJuestel** [cgre-aachen/gemgis#17]
A geotiff should be created from an array containing the information of the geological map. This should easily be done in rasterio. 

This goes back to the note created by @flohorovicic 

https://github.com/cgre-aachen/gempy/projects/18#card-33751728

**Comment by bluetyson** [comment]
Raster and vector outputs of everything sounds excellent!

**Comment by AlexanderJuestel** [comment]
Output of shape files, geojsons and geopackage for geological maps created in GemPy is available since yesterday :)

GeoTiff support will come at some point :)

**Comment by AlexanderJuestel** [comment]
Save geological map as tif is already implemented by saving an array as a raster

**Comment by bluetyson** [comment]
In an example?

**Comment by AlexanderJuestel** [comment]
Now, yes, I added it to the first tutorial at the bottom and to all examples in the example notebooks :)

**Comment by bluetyson** [comment]
Nice, will have a look tomorrow.
