### ISSUE TITLE
cutting off pyvista meshes with topography

### ISSUE THREAD

**Issue by mariuspischke** [cgre-aachen/gemgis#179]
Hey guys,
It could be helpful to write a function that cuts of pyvista meshes at topographic surfaces in order to visualize GemPy surfaces with pyvista.

Surfaces that for example have been created with GemPy can be visualized independently using PyVista. 
It would be cool to set up a digital elevation raster as a mesh, that cuts off meshes automatically at the right spot.

Cheers, 
Marius

**Comment by RichardScottOZ** [comment]
Will this work? https://docs.pyvista.org/examples/01-filter/clipping-with-surface.html

**Comment by mariuspischke** [comment]
Perfect. this was exactly what i was looking for! :)
Thanks a lot!

Cheers,
Marius
