### ISSUE TITLE
Integration with QGis

### ISSUE THREAD

**Issue by flohorovicic** [cgre-aachen/gemgis#18]
Test possibility for a tighter integration with QGis: reading shape files, exporting GeoTiffs back to project (similar to GE link)

**Comment by AlexanderJuestel** [comment]
I took the liberty to move this issue from GemPy to GemGIS as we are currently working on this integration.

**Comment by AlexanderJuestel** [comment]
Reading shape files is possible via geopandas, exporting GeoTiffs via rasterio is also possible for rasters and geological maps (both as np.ndarray)
