### ISSUE TITLE
Spaghetti_plots_for_analyzing_uncertainty_of_faults

### ISSUE THREAD

**Issue by Ali1990dashti** [cgre-aachen/gemgis#184]
**Is your feature request related to a problem? Please describe.**
Recently, I have been trying to show existing uncertainty in location, dip and direction of faults using gempy. Gempy is fantastic in doing it but I could not visualize the the uncertainty that much easily. 

**Describe the solution you'd like**
Sort of spaghetti plots can be usefull in visualizing perturbed fault/s in 3D models. Such postprocessing on Gempy results in GemGIS can make the uncertainty analysis more fluent.

**Additional context**
This simplified 2D section shows a spaghetti plot for 5 realizaions in which the location and dip of the fault is changing.

<img width="679" alt="spaghetti_plot" src="https://user-images.githubusercontent.com/62764899/128024311-f986c13c-ea87-4746-885a-64321daf7b76.png">

**Comment by AlexanderJuestel** [comment]
Issue will be closed for now

**Comment by AlexanderJuestel** [comment]
Hey @Ali1990dashti, 

I have recently added a new tutorial for creating Spaghetti Plots using GemPy. Hope this may still be useful for you!

https://gemgis.readthedocs.io/en/latest/getting_started/tutorial/57_creating_spaghetti_plots_in_gempy.html

**Comment by Ali1990dashti** [comment]
@AlexanderJuestel , Thanks a lot for the fantastic work.
I do appreciate your effort.
