### ISSUE TITLE
Add support of XML/KML files through remote-geomod

### ISSUE THREAD

**Issue by flohorovicic** [cgre-aachen/gemgis#19]
**Is your feature request related to a problem? Please describe.**
Methods to handle geographic data

**Describe the solution you'd like**
Handling different coordinate systems and projections, methods to read and translate different types of geographic information (kml-files, shape files, etc). 

**Describe alternatives you've considered**
n/a

**Additional context**
Can - at least partly - be based on remote-geomod, but surely needs a bit more thought for tighter integration.

**Comment by AlexanderJuestel** [comment]
- Integration of shape files done
- Integration of KML files seems trickey as of now

**Comment by AlexanderJuestel** [comment]
The title of the issue was changed to stress the feature that is suggested with this issue.

**Comment by AlexanderJuestel** [comment]
@flohorovicic, it seems like GeoPandas has a pretty good KML reader by now. Maybe that could be used instead of remote geomod :) If you could provide some sample files, I could wrap it in a nice little function :) 

```ruby
 import geopandas as gpd

  gpd.io.file.fiona.drvsupport.supported_drivers['KML'] = 'rw'
  df = gpd.read_file(file_path_in, driver='KML')
  df.to_file(out_shp)/df.to_file(file_path_out, driver="GeoJSON")
```

The code was found at https://github.com/giswqs/geemap/commit/c4c9e7d26cb2b7a4d76f1494b9784be6b5840f79

**Comment by AlexanderJuestel** [comment]
Tutorial 41 provides a short introduction on how to open KML data with Fiona and Geopandas. Closing this here now :)
