### ISSUE TITLE
JOSS review - Consider adding testing framework using GITHUB actions in addition to binder

### ISSUE THREAD

**Issue by kanishkan91** [cgre-aachen/gemgis#193]
Currently the testing framework environment used by this repository is binder. I would recommend that this also be implemented for Github actions. This may make it more robust to any failures introduced by future development. 

https://github.com/openjournals/joss-reviews/issues/3709

**Comment by AlexanderJuestel** [comment]
@kanishkan91 
There is a Github Action workflow for automated testing here: https://github.com/cgre-aachen/gemgis/blob/main/.github/workflows/testing.yml and the tests are located here: https://github.com/cgre-aachen/gemgis/tree/main/tests

Binder is not used for testing.
