### ISSUE TITLE
JOSS review: Explicit link to "vignette"

### ISSUE THREAD

**Issue by kanishkan91** [cgre-aachen/gemgis#199]
Instead of having an Example 1 in the documentation, the author can just create a vignette (i.e. a jupyter notebook similar to example 1) and add an explicit link to the same in the readme. This would make it easy for a new user to find as opposed to looking around in the documentation. This is an easy fix as the author can simply change the example to a vignette with some documentation edits and add an explicit link to the same in the readme. 

https://github.com/openjournals/joss-reviews/issues/3709

**Comment by AlexanderJuestel** [comment]
@kanishkan91 could you explain a little bit more how to do that?

**Comment by kanishkan91** [comment]
@AlexanderJuestel - Your main vignette (walk through example) is here - https://gemgis.readthedocs.io/en/latest/getting_started/examples/example01_parallel_inclined_layers.html. You can directly add a link to this from your readme. You can add a section called "vignette" or "example with walkthrough of gemgis" and just add a hyperlink to the example. Does this make sense?
