### ISSUE TITLE
How to create a mesh and import data in GemGis

### ISSUE THREAD

**Issue by jc-barreto** [cgre-aachen/gemgis#206]
I'm getting started with GemGis and I would like to reproduce something similar with [this example](https://gemgis.readthedocs.io/en/latest/getting_started/tutorial/35_plotting_borehole_data_with_pyvista.html), however, I don't know how to create the mesh in vtk file that is imported in the example. I have the topography of the place understudy in .dwg (autocad) file and I have cptu tests in excel (one sheet for each cptu), I have imported the cptu as pandas data frame in Jupyter, and I would like to plot all the cptu I have with the topography in 3D using GemGis. Is this possible? How can I do that?
There is any Youtube Channel with tutorial videos?

Thank you

**Comment by AlexanderJuestel** [comment]
Hello @jc-barreto, 

with mesh, do you mean the surface that is displayed? 

I have not worked with dwg files before. Can you post a sample of your data so I can test it?

Unfortunately, we haven't had the time to create any YouTube videos yet, sorry. 

Cheers
Alex

**Comment by jc-barreto** [comment]
Hello @AlexanderJuestel  Thank you for answering.

Yes, the mesh is the surface displayed.
I put the files [here](https://github.com/jc-barreto/GemGis_TEST_Jenny).
I really appreciate your help.

Cheers,

**Comment by bluetyson** [comment]
So you want a 3d plot based on elevation colormapped to the cptu?

**Comment by jc-barreto** [comment]
@bluetyson Yes, like the [example 35](https://gemgis.readthedocs.io/en/latest/getting_started/tutorial/35_plotting_borehole_data_with_pyvista.html)

**Comment by jc-barreto** [comment]
I did this in Jupyter notebook, with matplotlib, but without the surface from topography, I guess with GemGis will be bettter
![image](https://user-images.githubusercontent.com/42352209/149492170-3d532abf-3a32-4309-87d4-da37eebb42bf.png)

**Comment by RichardScottOZ** [comment]
Ok, I doubt too many of us have autocad - if you can convert the dwg into a standard sort of raster this is pretty straightforward.

![image](https://user-images.githubusercontent.com/72196131/149701726-5ab389d7-a7f1-4707-9347-4c7a0c1dc002.png)

Or something along these lines if not a tif:-
```python
def read_raster_depth(filename):
    """
    Helpful: http://xarray.pydata.org/en/stable/auto_gallery/plot_rasterio.html
    """
    # Read in the data
    data = xr.open_rasterio(filename)
    values = np.asarray(data)
    nans = values == data.nodatavals
    if np.any(nans):
        values = np.ma.masked_where(nans, values)
        values[nans] = np.nan
    # Make a mesh
    xx, yy = np.meshgrid(data['x'], data['y'])
    zz = values.reshape(xx.shape) # will make z-comp the values in the file
    # zz = np.zeros_like(xx) # or this will make it flat
    mesh = pv.StructuredGrid(xx, yy, zz)
    mesh['data'] = values.ravel(order='F')
    mesh['data'] = mesh['data'] * -1
    return mesh

dtm = read_raster_depth('topography.dwg')
dtm
```

**Comment by RichardScottOZ** [comment]
![image](https://user-images.githubusercontent.com/72196131/149702216-6c7f403c-8e60-42cf-98e0-538c9ccdf083.png)

**Comment by RichardScottOZ** [comment]
That would be assuming it is some sort of format like this, and not some multilayer vector type thing, like Alex, don't know about them.

**Comment by RichardScottOZ** [comment]
If that is the case and you can convert it to dxf you can do something like here:- https://gemgis.readthedocs.io/en/latest/getting_started/tutorial/27_opening_obj_and_dxf_files.html

**Comment by jc-barreto** [comment]
I have uploaded the topography as .dxf file [here](https://github.com/jc-barreto/GemGis_TEST_Jenny), but I don't understand how to import to gemgis my 2D topograph

**Comment by jc-barreto** [comment]
Is [this](https://www.youtube.com/watch?v=jkJTMd0C_6I) the kind of data I must have ?

**Comment by RichardScottOZ** [comment]
I think the Gemgis function wants all geometries the same @AlexanderJuestel ?  so it would have to match that

Is the topography something you created yourself?

**Comment by RichardScottOZ** [comment]
![image](https://user-images.githubusercontent.com/72196131/149849617-ccbce2f7-30f6-451d-b5ff-ea94d8afd454.png)

**Comment by jc-barreto** [comment]
No, this topography is from some project. I manage to import to ArcGis, I have georeferenceated, and now I have a raster and Tiff that I have exported from ArcGis, is this what is necessary? But the extension of the files after raster I don't understand, I have never worked with this before. 
![image](https://user-images.githubusercontent.com/42352209/149968421-ea625645-0e2c-42e4-aed6-a1113c96ea85.png)
Those are the files that I have exported when rastering with ArcGis
![image](https://user-images.githubusercontent.com/42352209/149968645-65142985-c3ca-4d0e-ba9b-2abd14a3ce27.png)

and those are the one I get when exporting as Tiff
![image](https://user-images.githubusercontent.com/42352209/149968736-f74e1383-a7f5-4b03-b7cf-60eee8185544.png)

What should I import em GemGis?

**Comment by AlexanderJuestel** [comment]
Hello @jc-barreto, 

these lines you are showing there look much like vector data and hence shape files. These can be used to create your topography. However, what you can do (at least in QGIS) is loading the .adf file and export it as .tif file, what you seem to have dones as well. This can then be loaded into GemGIS

**Comment by jc-barreto** [comment]
Hello @AlexanderJuestel  Thank you for the answer, so now I have to import my topo.tiff to gemgis, how can I do that?

**Comment by jc-barreto** [comment]
@AlexanderJuestel, thank you for the help.
Now I have the .tif file and I can import with rasterio, but I don't know how to create the mesh .vtk and and import the surface.
I have updated the files [here](https://github.com/jc-barreto/GemGis_TEST_Jenny), could you please help me reproduce example 35?
![image](https://user-images.githubusercontent.com/42352209/150128167-82bbfab5-de01-4178-8c86-adfc2bdcab34.png)

**Comment by AlexanderJuestel** [comment]
@jc-barreto,

You can follow this Tutorial that explains how to make a mesh out of your topography with PyVista: https://gemgis.readthedocs.io/en/latest/getting_started/tutorial/14_visualizing_topography_and_maps_with_pyvista.html

**Comment by jc-barreto** [comment]
Thank you, it works! Now, I'm finally following example 35, and I'm facing problems with the function gg.visualization.add_row_to_boreholes.
I have my topography
![image](https://user-images.githubusercontent.com/42352209/150158914-673a1edd-561d-4c3b-be03-ec7cd210da9c.png)

and my data
![image](https://user-images.githubusercontent.com/42352209/150159013-164ba839-67a4-4559-a308-97b8dc26ee83.png)

but when I try to run this part of the code: 
`list_df = gg.visualization.add_row_to_boreholes(df_groups)`
it gives this error:
![image](https://user-images.githubusercontent.com/42352209/150159290-6b661ba6-2c3f-4282-8379-c8722761ff9e.png)
The name of the columns in my table/data must be the same as in the example?

**Comment by bluetyson** [comment]
Or change it to reference the right column in your case

**Comment by jc-barreto** [comment]
Now, I have transformed my data to the same format/labeling that the example data, and still getting problems...
And I don't understand this error, because I have a pandas dataframe, and as it is printed, I have 8320 rows x 7 columns...
![image](https://user-images.githubusercontent.com/42352209/150323863-0055f6ae-8b80-4b91-800f-bf642d6c1e9c.png)

**Comment by AlexanderJuestel** [comment]
You are missing column Z, which is equal to the position of your stratigraphic interface. The depth column indicates the total depth of the well and should be the same for stratigraphic interfaces belonging to one well

**Comment by jc-barreto** [comment]
Z is not the altitude? I would like to plot my data for altitude, not for Z. and the depth is the total length of my borehole, for example, if I started to collect data from depth -16m to -24m, my depth is 8m? 
Those are my data, plotted with matplotlib(X,Y, Altitude, colored by formation), I would like to do the same but with GemGis, so I can include the topography

![image](https://user-images.githubusercontent.com/42352209/150338317-f9f318ab-bf8f-4764-bcab-dcb58d453ad1.png)

**Comment by jc-barreto** [comment]
I must say that GemGis is not straightforward, after a while I manage ( I think) to put my data in the right format:
![image](https://user-images.githubusercontent.com/42352209/150816427-3258d678-4299-4b9b-8c41-db18e1882987.png)

and now, I'm getting another error, even if my data is in the same format as the example...

![image](https://user-images.githubusercontent.com/42352209/150816726-855dfc14-e89e-48c0-9c91-0a895dc8dc53.png)

But I think I don't understand what is the 'altitude' in the code because is always the same for each borehole in the example and in my case change for each point. I don't know what I'm doing wrong

**Comment by RichardScottOZ** [comment]
Altitude or RL can be the height of the location of the drillhole at the surface.

Print the topo mesh and the tubes mesh out for us so we can see the dimensions/coordinates.

``` python
print(topo)
```

**Comment by RichardScottOZ** [comment]
or just that in a cell.

**Comment by AlexanderJuestel** [comment]
@jc-barreto I think you are almost there, would you mind sending me your data and I will have a look. It is sometimes easier to look at an issue locally :)

**Comment by jc-barreto** [comment]
@RichardScottOZ and @AlexanderJuestel Thank you for the help.
Here is the topo
![image](https://user-images.githubusercontent.com/42352209/150945525-e9c38daa-e492-4d70-8e56-02ce3ae50c9d.png)

And I put my data and the notebook I'm using [here](https://github.com/jc-barreto/GemGis_TEST_Jenny)

**Comment by RichardScottOZ** [comment]
thanks, what about the tubes?

Like Alex said, not too far off getting this to work

**Comment by jc-barreto** [comment]
![image](https://user-images.githubusercontent.com/42352209/150947477-3c1b7dd8-86e7-4edb-98b8-507bc233c177.png)

**Comment by RichardScottOZ** [comment]
something in the labels is odd by the looks?... min/max had nans anyway

as this works

![image](https://user-images.githubusercontent.com/72196131/150956929-ddedd9f5-31ff-4d4f-ad5f-bb553c6f2d2f.png)

**Comment by RichardScottOZ** [comment]
```python
def read_raster_depth(filename):
    """
    Helpful: http://xarray.pydata.org/en/stable/auto_gallery/plot_rasterio.html
    """
    # Read in the data
    data = xr.open_rasterio(filename)
    values = np.asarray(data)
    nans = values == data.nodatavals
    if np.any(nans):
        values = np.ma.masked_where(nans, values)
        values[nans] = np.nan
    # Make a mesh
    xx, yy = np.meshgrid(data['x'], data['y'])
    zz = values.reshape(xx.shape) # will make z-comp the values in the file
    # zz = np.zeros_like(xx) # or this will make it flat
    mesh = pv.StructuredGrid(xx, yy, zz)
    mesh['data'] = values.ravel(order='F')
    #mesh['data'] = mesh['data'] * -1
    return mesh

dem = read_raster_depth('topo_tiff.tif')
dem
```

**Comment by RichardScottOZ** [comment]
![image](https://user-images.githubusercontent.com/72196131/150957211-742d3c6e-8c63-4ab0-acd4-e3a8bf725117.png)

**Comment by RichardScottOZ** [comment]
![image](https://user-images.githubusercontent.com/72196131/150957321-45f8fa01-fcb3-48ba-ae31-29d36fb3aebf.png)

**Comment by jc-barreto** [comment]
I have checked the label and is fine, I also went through the code in Spyder, and from what I understood, to have nan in min/max is what should be?
![image](https://user-images.githubusercontent.com/42352209/151133517-abf7fee0-9569-4869-9fc1-c189f4caa25b.png)

So I don't understand why the label is not working, and why the boreholes are not showing the colors in the dictionary, this way I can't meet the goal: to be able to identify each borehole and each formation in depth

![image](https://user-images.githubusercontent.com/42352209/151133702-8009e0ff-128f-4de7-be30-60e3604c3418.png)

The updated Notebook is [here](https://github.com/jc-barreto/GemGis_TEST_Jenny)

**Comment by RichardScottOZ** [comment]
No, me either, so will have to dig into it.

**Comment by RichardScottOZ** [comment]
no labels
![image](https://user-images.githubusercontent.com/72196131/151153948-0695cf79-0e85-4904-a815-26c2f32aacdd.png)

**Comment by RichardScottOZ** [comment]
add labels 
![image](https://user-images.githubusercontent.com/72196131/151154037-1e1f902f-d117-48d7-a71f-2eff8769d18a.png)

**Comment by RichardScottOZ** [comment]
so labels have distorted this somehow

**Comment by RichardScottOZ** [comment]
Making them a bit bigger, labels clearly off in the corner for some reason 
![image](https://user-images.githubusercontent.com/72196131/151156089-413e7c22-a088-4d62-9820-8ebfd7af1b5f.png)

**Comment by AlexanderJuestel** [comment]
@jc-barreto are there any open questions here?
