### ISSUE TITLE
Create virtual borehole section using pyvista ray_trace

### ISSUE THREAD

**Issue by AlexanderJuestel** [cgre-aachen/gemgis#210]
Using PyVista `ray_trace` (https://docs.pyvista.org/api/core/_autosummary/pyvista.PolyData.ray_trace.html) we can pass the top and the bottom of a (vertical!) well and return the intersection this ray has with the surface and hence the well top that is needed.

Here, the result of such a function
![image](https://user-images.githubusercontent.com/45469915/158616471-1402fd80-4fba-4f27-a3ab-180692424de0.png)

Here, an example of a layer with the circled well (pyvista tube)
![image](https://user-images.githubusercontent.com/45469915/158616312-e0107601-0833-4fa4-a941-751afd313739.png)

@flohorovicic, @Japhiolite

**Comment by flohorovicic** [comment]
Awesome idea! 👍

**Comment by Japhiolite** [comment]
Nice, that has good potential for creating comparison plots between observed striplogs and simulated ones.

**Comment by AlexanderJuestel** [comment]
Implemented
