### ISSUE TITLE
 module 'gemgis.visualization' has no attribute 'create_lines_3d'

### ISSUE THREAD

**Issue by gostopy** [cgre-aachen/gemgis#214]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by AlexanderJuestel** [comment]
Dear @gostopy, thanks for opening your first issue. 

Could you please describe where you encountered the error? This would help us a lot. 

Cheers 
Alex

**Comment by AlexanderJuestel** [comment]
This was fixed in 1.0.1. The methods were refactored!
