### ISSUE TITLE
Unable to do Tutorial #42

### ISSUE THREAD

**Issue by vsharma-sonen** [cgre-aachen/gemgis#218]
**Describe the bug**

I am trying to reproduce https://gemgis.readthedocs.io/en/latest/getting_started/tutorial/42_draping_linestrings_over_dem_in_pyvista.html

When I try to do what is most likely the most critical part of the processing - I run into a bug 

boundary_points = gg.vector.extract_xyz(gdf=boundary_line, dem=raster, target_crs='EPSG:4647')

---> 

File ~/miniconda3/envs/qt_test/lib/python3.9/site-packages/gemgis/vector.py:1858, in extract_xyz(gdf, dem, minz, maxz, extent, reset_index, drop_index, drop_id, drop_points, drop_level0, drop_level1, target_crs, bbox, remove_total_bounds, threshold_bounds)
   1856 # Extracting xyz
   1857 if isinstance(dem, rasterio.io.DatasetReader):
-> 1858     gdf = extract_xyz_rasterio(gdf=gdf,
   1859                                dem=dem,
   1860                                reset_index=False,
   1861                                drop_id=False,
   1862                                drop_index=False,
   1863                                drop_level0=False,
   1864                                drop_level1=False,
   1865                                drop_points=False,
   1866                                remove_total_bounds=remove_total_bounds,
   1867                                threshold_bounds=threshold_bounds)
   1869 elif isinstance(dem, np.ndarray):
   1870     gdf = extract_xyz_array(gdf=gdf,
   1871                             dem=dem,
   1872                             extent=extent,
   (...)
   1879                             remove_total_bounds=remove_total_bounds,
   1880                             threshold_bounds=threshold_bounds)
...
---> 61     pts = zip(*filter(None, pts))
     63     for row_off, col_off in zip(*rowcol(dt, *pts)):
     64         if row_off < 0 or col_off < 0 or row_off >= height or col_off >= width:

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

<---

**Desktop (please complete the following information):**
 - OS: MacOSx
- Python: 3.9
- GEMGIS: 1.0.0 / 0.1.18

Thanks for any suggestions

**Comment by AlexanderJuestel** [comment]
@vsharma-sonen thanks for reporting. I will have a look!

**Comment by AlexanderJuestel** [comment]
@vsharma-sonen,

I re-run the tutorial and could not reproduce your error. Did you just run the tutorial or did you use your own data?

Could you also send more of the error message?

Cheers 
Alex
