### ISSUE TITLE
Parsing ESRI ASCII file fails if the file uses x / y corners instead of centers

### ISSUE THREAD

**Issue by Esras** [cgre-aachen/gemgis#220]
**Describe the bug**
While parsing an ASCII file format's headers, the `read_asc` function in `gemgis/raster.py` attempts to only use the `xllcenter` and `yllcenter` values. However, if the file specifies the corners and has the `cellsize` parameter _after_ the corners, then an `UnboundLocalError` is thrown, as `gemgis` tries to use the resolution to set the x and y centers, instead of storing the x and y corners.

**To Reproduce**
When parsing a file with the following format:
```
ncols         3
nrows         1
xllcorner     2.3
yllcorner     4.5
cellsize      12.3
NODATA_value  -9999
3 1 1
```
gemgis throws:

`UnboundLocalError: local variable 'res' referenced before assignment`

**Expected behavior**
gemgis does not throw an error.

**Potential Solution**
A quick solution that I ended up doing in my virtual env is the following:
```python
...
            if line_value == 'xllcorner':
                xllcorner = float(values[0])
            if line_value == 'yllcorner':
                yllcorner = float(values[0])
            ...
        # Outside the for loop, inside the file open context
        if res and xllcorner:
            xllcenter = float(xllcorner) + 0.5 * res

        if res and yllcorner:
            yllcenter = float(yllcorner) + 0.5 * res
```

**Comment by AlexanderJuestel** [comment]
Hello @Esras, 

thanks for reporting the issue. Would you mind opening a Pull Request fixing this?

Cheers
Alex

**Comment by Esras** [comment]
Sure, I can do that. I hadn't done that for this yet because I didn't know if there were other places in the code base that something like this might crop up or if there were other improvements that you might want to make with it.

I'll try to get to that this weekend.

**Comment by AlexanderJuestel** [comment]
@Esras, would you mind sending me your sample data? Then I could implement it quickly myself these days ;)

**Comment by Esras** [comment]
Sorry, been busy and dealing with being out of town. The data in the original message as well as the code there will fix the issue, but I wanted to review the codebase for other places like that. You might know better than me, obviously :)
