### ISSUE TITLE
Interpretation of ASCII data loses precision and generates wrongly-sized data

### ISSUE THREAD

**Issue by Esras** [cgre-aachen/gemgis#221]
**Describe the bug**
`gemgis` fails to generate a `PyVista` visualization on certain combinations of floating point values when reading and generating a structured grid from ASCII data. `PyVista` throws `ValueError: Input point array shapes must match exactly`.

**To Reproduce**
Test Case (`file.asc`):
```
ncols         3
nrows         1
xllcorner     2.3
yllcorner     4.5
cellsize      12.3
NODATA_value  -9999
3 1 1
```

The following should be a minimal reproduction with some output debugging to demonstrate:
```python
from pathlib import Path
import gemgis as gg
import numpy as np
import pyvista as pv

data = gg.raster.read_asc(path=Path('./file.asc'))
x_min = data['Extent'][0]
x_max = data['Extent'][1]
y_min = data['Extent'][2]
y_max = data['Extent'][3]

x = np.arange(x_min, x_max, data['Resolution'])
print(f"X Extents: ({x_min}, {x_max})")
print(f"NP X Ext: ({x[0]}, {x[-1]})")
print(f"Row Length from data: {len(data['Data'][0])}") # Length of a row (x)
print(f"Row Length from nump: {len(x)}")

y = np.arange(y_min, y_max, data['Resolution'])
print(f"Y Extents: ({y_min}, {y_max})")
print(f"NP Y Ext: ({x[0]}, {x[-1]})")
print(f"Col Length from data: {len(data['Data'])}") # Length of all rows (y)
print(f"Col Length from nump: {len(y)}")

grid = pv.StructuredGrid(x, y, data['Data'])
```

**Expected behavior**
There are the same number of generated cells as data in the original file.

**Additional context**
In NumPy's documentation for [arrange](https://numpy.org/doc/stable/reference/generated/numpy.arange.html), it is recommended only to be used when you have integer steps and instead to use `numpy.linspace`.

Since `linspace` takes in the number of steps, rather than a step, it may be worth adding the `nrows`/`ncols` to the dictionary of data that the `read_asc`  function returns. Alternatively, using the length of the data works:
```python
x_lin = np.linspace(x_min, x_max, len(data['Data'][0]))
y_lin = np.linspace(y_min, y_max, len(data['Data']))

x, y = np.meshgrid(x_lin, y_lin)

grid = pv.StructuredGrid(x, y, data['Data'])
```

**Comment by AlexanderJuestel** [comment]
Hey @Esras, 

was this related to #220? What is the status here?

**Comment by Esras** [comment]
This is not related to #220, the fix here is that any place where there is a range generated ussing numpy's `arange` function should instead be replaced with `linspace`. As with #220, though, I haven't had the time to dig into the code to see all the places where it might be used, and I would also want to generate / run tests against it.
