### ISSUE TITLE
Is there any plan to remove the pygeos from gemgis? 

### ISSUE THREAD

**Issue by brbr520** [cgre-aachen/gemgis#225]
Since pygeos has merged with shapely (http://[pygeos.readthedocs.io](http://pygeos.readthedocs.io/en/latest/)/en/latest/) in December 2021, will the GemGIS plan to remove the pygeos in the following new release? 
Currently in gemgis 1.0 there is an ImportError: The shaply GEOS version(3.11.1-CAPI-1.17.1) is incompatible with the GEOS version PyGEOS was compiled with(3.8.9=CAPI-1.13.1).

**Comment by AlexanderJuestel** [comment]
Hello @brbr520 , 

thanks for the issue! pygeos will be removed in a future release, yes. However, I have no schedule yet when this will happen but hopefully sooner rather than later!

**Comment by brbr520** [comment]
thanks @AlexanderJuestel ,
that sounds good. Hope for coming soon.

**Comment by AlexanderJuestel** [comment]
@brbr520, I have removed all pygeos reliects from gemgis in this commit: https://github.com/cgre-aachen/gemgis/commit/6265397bf2c7ce7210e9ccd868ffb8840415afbd

I will merge it soon!

**Comment by AlexanderJuestel** [comment]
pygeos was removed from GemGIS. GemGIS is now using Shapely 2.0. This was introduced in version 1.0.1 of GemGIS now
