### ISSUE TITLE
[DOC] Suggestion for updating the GemGIS Documentation

### ISSUE THREAD

**Issue by JanWagner1312** [cgre-aachen/gemgis#232]
This feature request is supposed to be an extensive list of suggestions for updating the GemGIS Documentation

- [x] Front Page: Make each major point a bullet point, that can 1) be extended to reveal the sub-topics, and 2) act as a link to the topic.
- [x] Change "About GemGis Installation Tutorials Examples" - for example: "About GemGis | Installation | Tutorials | Examples" 
- [x] Make the link to GitHub more obvious (add to Frontpage instead of "Read the Docs") (?)
- [x] Add API Reference to Docs

Please feel free to comment on these ideas or add further suggestions

**Comment by AlexanderJuestel** [comment]
I was finally able to add an API reference to the docs, locally for now but this should be a feature for GemGIS 1.1

![image](https://github.com/cgre-aachen/gemgis/assets/45469915/c5bcbc68-7e85-4063-be33-81abac42460e)

**Comment by AlexanderJuestel** [comment]
Task list to track the progress of editing the docstrings of the `gemgis.vector` methods
- [ ]  'calculate_angle',
- [ ]  'calculate_azimuth',
- [ ]  'calculate_coordinates_for_linestring_on_cross_sections',
- [ ]  'calculate_coordinates_for_linestrings_on_cross_sections',
- [ ]  'calculate_coordinates_for_point_on_cross_section',
- [ ]  'calculate_dipping_angle_linestring',
- [ ]  'calculate_dipping_angles_linestrings',
- [ ]  'calculate_distance_linestrings',
- [ ]  'calculate_midpoint_linestring',
- [ ]  'calculate_midpoints_linestrings',
- [ ]  'calculate_orientation_for_three_point_problem',
- [ ]  'calculate_orientation_from_bent_cross_section',
- [ ]  'calculate_orientation_from_cross_section',
- [ ]  'calculate_orientations_from_cross_section',
- [ ]  'calculate_orientations_from_strike_lines',
- [ ]  'calculate_strike_direction_bent_linestring',
- [ ]  'calculate_strike_direction_straight_linestring',
- [ ]  'clip_by_bbox',
- [ ]  'clip_by_polygon',
- [ ]  'create_bbox',
- [ ]  'create_buffer',
- [ ]  'create_hexagon',
- [ ]  'create_hexagon_grid',
- [ ]  'create_linestring_from_points',
- [ ]  'create_linestring_from_xyz_points',
- [ ]  'create_linestring_gdf',
- [ ]  'create_linestrings_from_contours',
- [ ]  'create_linestrings_from_xyz_points',
- [ ]  'create_polygons_from_faces',
- [ ]  'create_unified_buffer',
- [ ]  'explode_geometry_collection',
- [ ]  'explode_geometry_collections',
- [ ]  'explode_linestring',
- [ ]  'explode_linestring_to_elements',
- [ ]  'explode_multilinestring',
- [ ]  'explode_multilinestrings',
- [ ]  'explode_polygon',
- [ ]  'explode_polygons',
- [ ]  'extract_interfaces_coordinates_from_cross_section',
- [ ]  'extract_orientations_from_cross_sections',
- [ ]  'extract_orientations_from_map',
- [ ]  'extract_xy',
- [ ]  'extract_xy_from_polygon_intersections',
- [ ]  'extract_xy_linestring',
- [ ]  'extract_xy_linestrings',
- [ ]  'extract_xy_points',
- [ ]  'extract_xyz',
- [ ]  'extract_xyz_array',
- [ ]  'extract_xyz_from_cross_sections',
- [ ]  'extract_xyz_linestrings',
- [ ]  'extract_xyz_points',
- [ ]  'extract_xyz_polygons',
- [ ]  'extract_xyz_rasterio',
- [ ]  'interpolate_raster',
- [ ]  'intersection_polygon_polygon',
- [ ]  'intersections_polygon_polygons',
- [ ]  'intersections_polygons_polygons',
- [ ]  'load_gpx',
- [ ]  'load_gpx_as_dict',
- [ ]  'load_gpx_as_geometry',
- [ ]  'remove_interfaces_within_fault_buffers',
- [ ]  'remove_object_within_buffer',
- [ ]  'remove_objects_within_buffer',
- [ ]  'sample_from_array',
- [ ]  'sample_from_rasterio',
- [ ]  'set_dtype',
- [ ]  'sort_by_stratigraphy',
- [ ]  'subtract_geom_objects',
- [ ]  'unify_linestrings',
- [ ]  'unify_polygons'

​

**Comment by AlexanderJuestel** [comment]
- [ ]  'calculate_aspect',
- [ ]  'calculate_default_transform',
- [ ]  'calculate_difference',
- [ ]  'calculate_hillshades',
- [ ]  'calculate_slope',
- [ ]  'clip_by_bbox',
- [ ]  'clip_by_polygon',
- [ ]  'create_filepaths',
- [ ]  'create_src_list',
- [ ]  'dtype_conversion',
- [ ]  'extract_contour_lines_from_raster',
- [ ]  'glob',
- [ ]  'gpd',
- [ ]  'mask',
- [ ]  'merge',
- [ ]  'merge_tiles',
- [ ]  'np',
- [ ]  'os',
- [ ]  'pd',
- [ ]  'pyproj',
- [ ]  'rasterio',
- [ ]  'read_asc',
- [ ]  'read_msh',
- [ ]  'read_ts',
- [ ]  'read_zmap',
- [ ]  'reproject',
- [ ]  'reproject_raster',
- [ ]  'resize_by_array',
- [ ]  'resize_raster',
- [ ]  'sample_from_array',
- [ ]  'sample_from_rasterio',
- [ ]  'sample_interfaces',
- [ ]  'sample_orientations',
- [ ]  'sample_randomly',
- [ ]  'save_as_tiff',
- [ ]  'shapely'

**Comment by AlexanderJuestel** [comment]
- [ ]  'add_row_to_boreholes',
- [ ]  'calculate_vector',
- [ ]  'clip_seismic_data',
- [ ]  'convert_to_rgb',
- [ ]  'create_borehole_labels',
- [ ]  'create_borehole_tube',
- [ ]  'create_borehole_tubes',
- [ ]  'create_boreholes_3d',
- [ ]  'create_delaunay_mesh_from_gdf',
- [ ]  'create_dem_3d',
- [ ]  'create_depth_map',
- [ ]  'create_depth_maps_from_gempy',
- [ ]  'create_deviated_borehole_df',
- [ ]  'create_deviated_boreholes_3d',
- [ ]  'create_lines_3d_linestrings',
- [ ]  'create_lines_3d_polydata',
- [ ]  'create_lines_from_points',
- [ ]  'create_mesh_from_cross_section',
- [ ]  'create_meshes_from_cross_sections',
- [ ]  'create_meshes_hypocenters',
- [ ]  'create_points_3d',
- [ ]  'create_polydata_from_dxf',
- [ ]  'create_polydata_from_msh',
- [ ]  'create_polydata_from_ts',
- [ ]  'create_structured_grid_from_asc',
- [ ]  'create_structured_grid_from_zmap',
- [ ]  'create_temperature_map',
- [ ]  'create_thickness_maps',
- [ ]  'drape_array_over_dem',
- [ ]  'extract_xy',
- [ ]  'extract_xyz',
- [ ]  'get_batlow_cmap',
- [ ]  'get_color_lot',
- [ ]  'get_mesh_geological_map',
- [ ]  'get_petrel_cmap',
- [ ]  'get_points_along_spline',
- [ ]  'get_seismic_cmap',
- [ ]  'group_borehole_dataframe',
- [ ]  'plane_through_hypocenters',
- [ ]  'plot_data',
- [ ]  'plot_orientations',
- [ ]  'polyline_from_points',
- [ ]  'read_raster',
- [ ]  'resample_between_well_deviation_points',
- [ ]  'sample_from_rasterio',
- [ ]  'seismic_to_array',
- [ ]  'seismic_to_mesh',
- [ ]  'set_extent',
- [ ]  'show_well_log_along_well'

**Comment by AlexanderJuestel** [comment]
- [ ]  'assign_properties',
- [ ]  'box',
- [ ]  'build_style_dict',
- [ ]  'calculate_lines',
- [ ]  'calculate_number_of_isopoints',
- [ ]  'convert_location_dict_to_gdf',
- [ ]  'convert_to_gempy_df',
- [ ]  'convert_to_petrel_points_with_attributes',
- [ ]  'create_polygon_from_location',
- [ ]  'create_surface_color_dict',
- [ ]  'create_virtual_profile',
- [ ]  'create_zmap_grid',
- [ ]  'extract_zmap_data',
- [ ]  'get_location_coordinate',
- [ ]  'get_locations',
- [ ]  'get_nearest_neighbor',
- [ ]  'getfeatures',
- [ ]  'interpolate_strike_lines',
- [ ]  'load_surface_colors',
- [ ]  'parse_categorized_qml',
- [ ]  'ray_trace_multiple_surfaces',
- [ ]  'ray_trace_one_surface',
- [ ]  'read_csv_as_gdf',
- [ ]  'save_zmap_grid',
- [ ]  'set_extent',
- [ ]  'set_resolution',
- [ ]  'show_number_of_data_points',
- [ ]  'to_section_dict',
- [ ]  'transform_location_coordinate',

**Comment by AlexanderJuestel** [comment]
- [ ] 'create_request',
- [ ]  'load_as_array',
- [ ]  'load_as_file',
- [ ]  'load_as_files',
- [ ]  'load_as_gpd',
- [ ]  'load_as_map',
- [ ]  'load_wcs',
- [ ]  'load_wfs',
- [ ]  'load_wms'

**Comment by AlexanderJuestel** [comment]
- [ ] 'get_meta_data',
- [ ]  'get_meta_data_df',
- [ ]  'get_stratigraphic_data',
- [ ]  'get_stratigraphic_data_df',
- [ ]  'load_formations',
- [ ]  'load_pdf',
- [ ]  'load_symbols',

**Comment by AlexanderJuestel** [comment]
- [ ]  'calculate_dip_and_azimuth_from_mesh',
- [ ]  'create_attributes',
- [ ]  'create_subelement',
- [ ]  'create_symbol',
- [ ]  'crop_block_to_topography',
- [ ]  'extract_borehole',
- [ ]  'extract_lithologies',
- [ ]  'extract_orientations_from_mesh',
- [ ]  'save_model',
- [ ]  'save_qgis_qml_file',

**Comment by AlexanderJuestel** [comment]
The API Reference is now online
