### ISSUE TITLE
DEM distorted when plotting

### ISSUE THREAD

**Issue by Magio94** [cgre-aachen/gemgis#241]
Good morning,

I’m trying to use your library, but when I try to load a DEM it is distorted. It remains much higher and stronger on the Z axis than it really is

**Comment by AlexanderJuestel** [comment]
Hello @Magio94,

Thanks for opening the issue. Could you provide us with the code you used to open the raster and even send us the raster if it is not too big?

I have a feeling where an error might be.

Cheers Alex

**Comment by Magio94** [comment]
I think the error is on the structure of the dem as I am uploading it. 

The original dem is here: https://www.dropbox.com/s/npp1ty9vm19hh69/Calabria.tif?dl=0

And the file I cut with the code: https://www.dropbox.com/t/llotpWHRZ7AtrinR

Thank you

**Comment by AlexanderJuestel** [comment]
Hey @Magio94

Could you just copy the lines of code here into the issue from where you open the raster to where you plot it.

Thanks
Cheers
Alex

**Comment by Magio94** [comment]
I just applied the example on the website to mine dem 

sargs = dict(fmt="%.0f", color='black')

p = pv.Plotter(notebook=True)

# Adding DEM
p.add_mesh(topo, scalars='Elevation [m]', cmap='gist_earth', scalar_bar_args=sargs, clim=[-100, 500])

# Adding boundary
#p.add_mesh(boundary_pv, color='blue', line_width=5)

# Adding faults
#p.add_mesh(faults_pv,color='red', line_width=2)

p.set_background('white')
p.show_grid(color='black')
p.set_scale(1,1,10)
p.show()

**Comment by AlexanderJuestel** [comment]
Hello @Magio94,

If you just copy and paste the code, then you have missed the scaling factor of 15 that was applied to the sample mesh loaded in line 6. Just change it to 1 and your Rast should plot just fine.

**Comment by Magio94** [comment]
@AlexanderJuestel thanks for your patience. These are basic things but I don’t have a lot of experience in Python and I’m still learning.

**Comment by AlexanderJuestel** [comment]
Hello @Magio94,

No problem, feel free to open a new issue if you have any other questions.

**Comment by AlexanderJuestel** [comment]
Hey, could you elaborate more on that package? I do not know it.
