### ISSUE TITLE
extract_contour_lines_from_raster not working because of skimage dependency

### ISSUE THREAD

**Issue by JanWagner1312** [cgre-aachen/gemgis#257]
**Describe the bug**
function extract_contour_lines_from_raster is not working as intended due to skimage being used in the function but not being a set dependency in gemgis. 

![image](https://user-images.githubusercontent.com/122881736/220319650-114d3909-917b-4c79-86b3-0c43eed62e94.png)

**Comment by AlexanderJuestel** [comment]
Fixed in #258
