### ISSUE TITLE
[ENH] Return lith_block cropped to topography using pvgeo

### ISSUE THREAD

**Issue by cfandel** [cgre-aachen/gemgis#259]
Putting this in a separate issue since it's just a small question. :)

Is it possible to return a lithology array where all cells above the land surface have been filled with NaNs or zeros?
It looks like you have something set up for it with `sol.mask_topo()`, but there's not quite enough documentation for me to figure out how to do it.
`sol.mask_topo(sol.mask_matrix)` gives me a dimension error because one is 1D and one is 3D.

**Comment by AlexanderJuestel** [comment]
@cfandel, @MTurner439,

I transfered your issue to our GemGIS repository as I thought that it could be a nice addition to the repo and as it is not entirely within the scope of GemPy

**Comment by AlexanderJuestel** [comment]
I could nicely reproduce your suggestion using PVgeo 
![image](https://user-images.githubusercontent.com/45469915/221018845-8fd5ab24-1e3d-4c86-be40-b0d13ecd9655.png)

**Comment by AlexanderJuestel** [comment]
```python

import pyvista as pv
 
# Computing model
sol = gp.compute_model(geo_model, compute_mesh=True)

# Creating StructuredGrid
grid = pv.UniformGrid()

# Set Grid Dimensions
grid.dimensions= np.array(sol.lith_block.shape)+1

# Set Grid Origin
grid.origin = (0,0,300)  # The bottom left corner of the data set

# Set Grid Spacing
grid.spacing = (972/50, 1069/50, 500/50) # The cell size

# Set Cell Data
grid.cell_data['values']= sol.lith_block.flatten(order='F')

# Extracting Topography values 
topography = geo_model._grid.topography.values

# Creating Polydata Dataset
topo = pv.PolyData(topography)

# Interpolating topography 
topo.delaunay_2d(inplace=True)


from PVGeo.grids import ExtractTopography

extracted = ExtractTopography(tolerance=5, remove=True).apply(grid, topo)
extracted.plot(scalars="Extracted")


p = pv.Plotter(notebook=False)
p.add_mesh(topo, cmap="gist_earth", opacity=0.8)
p.add_mesh(extracted, scalars='values',color=True, show_edges=True, opacity=1)
p.show_grid()
p.show()

```

**Comment by AlexanderJuestel** [comment]
Closing as this was added in #255
