### ISSUE TITLE
[DEP] Dependency questions

### ISSUE THREAD

**Issue by DManowitz** [cgre-aachen/gemgis#282]
**What is your question?**
I installed gemgis in a conda environment, and I got the following error when trying to import gemgis:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\manow\miniconda3\envs\py38_ml_TfGpuMain\lib\site-packages\gemgis\__init__.py", line 37, in <module>
    import gemgis.visualization as visualization
  File "C:\Users\manow\miniconda3\envs\py38_ml_TfGpuMain\lib\site-packages\gemgis\visualization.py", line 779, in <module>
    zmax: Union[float, int] = 1000) -> Tuple[pv.core.pointset.PolyData, pv.core.objects.Texture]:
AttributeError: module 'pyvista.core.objects' has no attribute 'Texture'
```

I then noticed that your requirements.txt file specifies specific versions of dependencies, whereas the conda-forge packages only list the existence of dependent packages (other than python >=3.6).

Would it be possible to bring your dependency requirements in sync between PyPi and conda-forge to ensure that those installing this package from conda-forge install the correct dependencies?  Furthermore, would it be possible to have your requirements be more loose than having specific versions of packages as dependencies so that this package could be better installed along with other packages?

**Comment by AlexanderJuestel** [comment]
@DManowitz

Thanks for your question, this is indeed a bug that I will fix shortly (tomorrow).

Thanks for mentioning the the versions for the dependencies. I will have a look at them tomorrow as well!

Cheers
Alex

**Comment by AlexanderJuestel** [comment]
Dear @DManowitz, 

I just released GemGIS version 1.0.10. Please update GemGIS using pip and let me know if the issue is still present

**Comment by DManowitz** [comment]
I tried GemGIS v1.0.10 from PyPi, and I got the following error when trying to import it:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "...\lib\site-packages\gemgis\__init__.py", line 37, in <module>
    import gemgis.visualization as visualization
  File "...\lib\site-packages\gemgis\visualization.py", line 4637, in <module>
    dist: np.ndarray) -> pv.core.pyvista_ndarray.pyvista_ndarray:
AttributeError: type object 'pyvista_ndarray' has no attribute 'pyvista_ndarray'
```

I did figure out that GemGIS v1.0.9 is not compatible with pyvista v0.39.0, though.  Installing pyvista v0.38.6 allowed me to import gemgis without getting the error I originally reported.

**Comment by AlexanderJuestel** [comment]
Please update to GemGIS 1.0.11 to see if the error is still present

**Comment by DManowitz** [comment]
GemGIS 1.0.11 imports with pyvista versions 0.38.6, 0.39.0, and 0.39.1.  Will you also push this version to conda-forge?

**Comment by AlexanderJuestel** [comment]
Yes, will do so tomorrow

**Comment by AlexanderJuestel** [comment]
@DManowitz were you able to upgrade to GemGIS 1.0.11?

**Comment by DManowitz** [comment]
Yes, I was able to upgrade to GemGIS 1.0.11.  Thank you.

**Comment by AlexanderJuestel** [comment]
Please feel free to reopen if any issues arise.
