### ISSUE TITLE
[ENH] Issue by draping the image of a map over DEM

### ISSUE THREAD

**Issue by ccastelblanco** [cgre-aachen/gemgis#287]
Hi,

I am currently trying to drape the image of a georeferenced geological map over a DEM, using GemGIS but I get the following error message:

"ValueError                                Traceback (most recent call last)
Cell In[4], line 1
----> 1 mesh, texture = gg.visualization.drape_array_over_dem(dem=dem,
      2                                                       array=crop_img)

File [c:\Users\carli\anaconda3\envs\gemgis\lib\site-packages\gemgis\visualization.py:892](file:///C:/Users/carli/anaconda3/envs/gemgis/lib/site-packages/gemgis/visualization.py:892), in drape_array_over_dem(array, dem, extent, zmax)
    889 elevation[elevation > zmax] = 0
    891 # Creating StructuredGrid
--> 892 mesh = pv.StructuredGrid(x, y, np.flipud(elevation))
    893 mesh.texture_map_to_plane(inplace=True)
    894 texture = pv.numpy_to_texture(array)

File [c:\Users\carli\anaconda3\envs\gemgis\lib\site-packages\pyvista\core\pointset.py:2004](file:///C:/Users/carli/anaconda3/envs/gemgis/lib/site-packages/pyvista/core/pointset.py:2004), in StructuredGrid.__init__(self, uinput, y, z, deep, *args, **kwargs)
   1998     self._from_file(uinput, **kwargs)
   1999 elif (
   2000     isinstance(uinput, np.ndarray)
   2001     and isinstance(y, np.ndarray)
   2002     and isinstance(z, np.ndarray)
   2003 ):
-> 2004     self._from_arrays(uinput, y, z, **kwargs)
   2005 elif isinstance(uinput, np.ndarray) and y is None and z is None:
   2006     self.points = uinput  # type: ignore

File [c:\Users\carli\anaconda3\envs\gemgis\lib\site-packages\pyvista\core\pointset.py:2050](file:///C:/Users/carli/anaconda3/envs/gemgis/lib/site-packages/pyvista/core/pointset.py:2050), in StructuredGrid._from_arrays(self, x, y, z, force_float)
...
-> 2050     raise ValueError('Input point array shapes must match exactly')
   2052 # make the output points the same precision as the input arrays
   2053 points = np.empty((x.size, 3), x.dtype)

ValueError: Input point array shapes must match exactly"

The image is a GeoTIFF file that was read by using io from skimage. The array was cropped to match the DEM coordinate bounds. The DEM shape is (264,360) and the image shape is (4396, 5444, 3).

I appreciate your kind help to fix this.

Regards,

**Comment by AlexanderJuestel** [comment]
Hello @ccastelblanco,

I will get back to you on Monday and see what we can do to fix your issue :)

Cheers
Alex

**Comment by AlexanderJuestel** [comment]
Also relates to #273

**Comment by AlexanderJuestel** [comment]
You could also try to resize your raster using

```python
array_resized = resize(image=crop_img.read(1),
                           output_shape=(dem.shape[0], dem.shape[1]))
array_resized
```

and pass `array_resized` to `drape_array_over_dem`.

Let me know if that worked. I will implement that in the function for the next release as well.

**Comment by ccastelblanco** [comment]
Thank you very much for your suggestion.  I resized the raster and it worked!
