### ISSUE TITLE
Terminology - energy/mining

### ISSUE THREAD

**Issue by bluetyson** [cgre-aachen/gemgis#29]
Just a style thing, but I noticed 'wells' mentioned.  e.g. not everything under the ground is liquid?  So could make that more general?

**Comment by AlexanderJuestel** [comment]
Good point (talking to a guy who wants to go into geothermal energy ;) )!

**Comment by AlexanderJuestel** [comment]
We should have changed all "wells" to boreholes. If you find any other inconsistencies, let us know :)
