### ISSUE TITLE
[ENH] Implement CRS reprojection for seismic data (SEGY)

### ISSUE THREAD

**Issue by KetMic** [cgre-aachen/gemgis#300]
**Is your feature request related to a problem? Please describe.**
Seismic data (SEGY) from different providers/projects are often not in the same CRS. To load them in a single project, many softwares required a consistent CRS of all data. Reprojections between CRS of SEGY files is required.

**Describe the solution you'd like**
Reprojection of shot point locations from one CRS to another in a SEGY file would be extremely useful.

**Comment by AlexanderJuestel** [comment]
Added in #299
