### ISSUE TITLE
conflicts between gemgis and pandas

### ISSUE THREAD

**Issue by ada-hou** [cgre-aachen/gemgis#326]
**Describe the bug**
After import gemgis, pandas only retains two decimal places.
**To Reproduce**
pandans = 2.0.1
gemgis = 1.1.8

code:
`import pandas as pd

aaa = [[111.8065315459521, 36.86729095761402]]

print("Using Pandas:")
print(pd.DataFrame(data=aaa))

import gemgis
print("\nUsing gemgis:")
print(pd.DataFrame(data=aaa))
`

result:

Using Pandas:
            0          1
0  111.806532  36.867291

Using gemgis:
       0     1
0 111.81 36.87

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [macOS]
 - Version [10.15]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by AlexanderJuestel** [comment]
Hello, 
are you using any GemGIS function?

**Comment by ada-hou** [comment]
![image](https://github.com/cgre-aachen/gemgis/assets/18135689/836595c5-c612-427c-b529-002f2a492776)
I found the setting of pd in Gemgis

**Comment by ada-hou** [comment]
But I found a new problem, I re -initiated an issue
