### ISSUE TITLE
Add support to read CSV files as GDF

### ISSUE THREAD

**Issue by AlexanderJuestel** [cgre-aachen/gemgis#34]
We should be able to read CSV files with Pandas, assign a geometry column and crs and return a GeoDataFrame

See here: 

https://github.com/cgre-aachen/gemgis/blob/3f0fe5308cacfbd5db0cee1196deb9fc3ef9a88c/gemgis/utils.py#L642-L649

**Comment by bluetyson** [comment]
Good idea. Nice function for people to have.

**Comment by AlexanderJuestel** [comment]
Implemented in GemPy 0.1.1
