### ISSUE TITLE
Thickness and Depth Maps for geological Interpretations

### ISSUE THREAD

**Issue by AlexanderJuestel** [cgre-aachen/gemgis#37]
**Is your feature request related to a problem? Please describe.**
For a geologist, it is vital to describe the **depth of a layer** in the underground. This could be relevant for geothermal exploration (depth of the target layers) or in general to describe the setting of a layer. 
In addition, the thickness of a layer may provide insights about local depocenters or just how thick the layer is across the whole model area (where does my reservoir have the highest thickness).

**Describe the solution you'd like**
It would be great to have the possibility to plot the surface and its color as a function of the depth or thickness like commercial software is capable of. This could go in hand with a better method to select single layers for plotting next `plot_all_surfaces`. 

**Describe alternatives you've considered**
None but it should be fairly simple if one can access the different meshes and their attributes...

**Comment by bluetyson** [comment]
Depth definitely relevant for drilling!

**Comment by AlexanderJuestel** [comment]
Agree, as you can see I figured out how to create the depth maps already. However, vertices and edges are not returned in the current versions of GemPy 2.2.3 for some reason (https://github.com/cgre-aachen/gempy/issues/494).

As soon as that is fixed, we should be able to quickly implement it and apply it to the current example models ;)

**Comment by AlexanderJuestel** [comment]
cgre-aachen/gempy#494 was fixed by updating skimage to version 0.17.2

**Comment by AlexanderJuestel** [comment]
Closing this as depth and thickness maps seem to work now :)
