### ISSUE TITLE
Load Elevation from WMS

### ISSUE THREAD

**Issue by domist07** [cgre-aachen/gemgis#56]
(How) is it possible to get the absolute elevation of my pixels in the picture? With `load_as_map` or `load_as_array` I only get the relative values as colours.
I want to use a WMS as  a digital terrain model (DTM).

**Comment by AlexanderJuestel** [comment]
Hey, 

yeah, we are aware of that issue. It seems like the WMS layers only store the color values. If you have the min and max values of your raster you could convert the heights. 

An alternative would be WCS layers (web coverage services). They also contain the height data. OWSLib supports requesting WCS data but for WCS layers of the state of NRW it does not work for instance. So, we are thinking of implementing our own solution at some point to automate that. 

Sorry to be not of more help right now.
Alex

**Comment by AlexanderJuestel** [comment]
I have requested assistance on how to get the elevation data from WMS Services loaded with OWSLib. I will keep you posted once I get an answer from them :)

**Comment by bluetyson** [comment]
There's  a grab a DTM example in map2loop, too polygon_ll=polygon.to_crs(src_crs)

minlong=polygon_ll.total_bounds[0]-step_out
maxlong=polygon_ll.total_bounds[2]+step_out
minlat=polygon_ll.total_bounds[1]-step_out
maxlat=polygon_ll.total_bounds[3]+step_out

print(minlong,maxlong,minlat,maxlat)
downloaded = False
i=0
print('Attempt: 0 ',end='')
while downloaded == False:
    try:
        m2l_utils.get_dtm(dtm_file, minlong,maxlong,minlat,maxlat)
        downloaded=True
    except:
        time.sleep(10)
        i=i+1
        print(' ',i,end='')
if(i==100):
    raise NameError('map2loop error: Could not access DTM server after 100 attempts')
print()

geom_rp=m2l_utils.reproject_dtm(dtm_file,dtm_reproj_file,src_crs,dst_crs)

dtm = rasterio.open(dtm_reproj_file)
pyplot.imshow(dtm.read(

**Comment by bluetyson** [comment]
WMS store pictures not data so you'd have to hack it to grayscale singleband to use in the interim

**Comment by bluetyson** [comment]
https://github.com/Loop3D/map2loop/blob/master/map2loop/m2l_utils.py

############################################
# get dtm data from Hawaiian SRTM server and save as geotiff
#
# get_dtm_hawaii(dtm_file, minlong,maxlong,minlat,maxlat)
# Args:
# dtm_file path to location where geotiff of elevation will be saved (in WGS84 lat/long) minlong,maxlong,minlat,maxlat min/max coordinates of region of interest
# minlong,maxlong,minlat,maxlat bounding coordinates in at/long
#
# Extracts and saves to file digital terrain model from GA hosted data for Australia. Highest horizontal resolution is ? m. Min/max lat/long in WGS84 dtm_file is relative path filename.
############################################
def get_dtm_hawaii(path_out, minlong,maxlong,minlat,maxlat):
    
    step_out=0
    minxll=int(((minlong+180)*120)-step_out)
    maxxll=int(((maxlong+180)*120)+step_out)
    minyll=int(((minlat+90)*120)-step_out)
    maxyll=int(((maxlat+90)*120)+step_out)  
      
    sizex=round(maxxll-minxll+1)
    sizey=round(maxyll-minyll+1)
    
    minxll=str(minxll)
    maxxll=str(maxxll)
    minyll=str(minyll)
    maxyll=str(maxyll)
    bbox="["+minyll+":1:"+maxyll+"]["+minxll+":1:"+maxxll+"]"

    link = "https://pae-paha.pacioos.hawaii.edu/thredds/dodsC/srtm30plus_v11_land.ascii?elev"+bbox
    print(link)
    f = urlopen(link)
    myfile = f.read()
    myfile2=myfile.decode("utf-8") 
    data=myfile2.split("---------------------------------------------")
    #import re

    grid=re.sub('\[.*\]','',data[1]).replace(",","").replace("elev.elev","").replace("\n"," ").replace("  "," ")
    #print(grid)
    grid=grid.split(" ")
    grid=grid[2:(sizex*sizey)+2]
    
    #OPeNDAP = np.ones((sizey,sizex), dtype='int16')
    #k=0
    #for j in range (0, sizey, 1):
    #    for i in range (0, sizex, 1):
    #        OPeNDAP[sizey-1-j][i]=int(float(grid[k]))
    #        k+=1

    OPeNDAP=np.asarray(grid,dtype=np.float16).reshape(sizey,sizex)
    OPeNDAP=OPeNDAP.astype('int16')
    OPeNDAP=np.flipud(OPeNDAP)


    transform = from_origin(minlong, maxlat,0.008333333,0.008333333)

    new_dataset = rasterio.open(path_out, 'w', driver='GTiff',
                                height = OPeNDAP.shape[0], width = OPeNDAP.shape[1],
                                count=1, dtype=str(OPeNDAP.dtype),
                                crs='+proj=longlat',
                                transform=transform)

    new_dataset.write(OPeNDAP, 1)
    new_dataset.close()
    print("dtm geotif saved as",path_out)

############################################
# get dtm data from GA SRTM server and save as geotiff
#
# get_dtm(dtm_file, minlong,maxlong,minlat,maxlat)
# Args:
# dtm_file path to location where geotiff of elevation will be saved (in WGS84 lat/long) minlong,maxlong,minlat,maxlat min/max coordinates of region of interest
# minlong,maxlong,minlat,maxlat bounding coordinates in at/long
#
# Extracts and saves to file digital terrain model from GA hosted data for Australia. Highest horizontal resolution is ? m. Min/max lat/long in WGS84 dtm_file is relative path filename.
############################################
def get_dtm(path_out, minlong,maxlong,minlat,maxlat):


    bbox=(minlong,minlat,maxlong,maxlat)

    url="http://services.ga.gov.au/gis/services/DEM_SRTM_1Second_over_Bathymetry_Topography/MapServer/WCSServer?"
    wcs = WebCoverageService(url,version='1.0.0')

    cvg=wcs.getCoverage(identifier='1',  bbox=bbox, format='GeoTIFF', crs=4326, width=200, height=200)

    f = open(path_out, 'wb')
    bytes_written = f.write(cvg.read())
    f.close()
    print("dtm geotif saved as",path_out)
    
############################################
#reproject a dtm 
#
# reproject_dtm(dtm_file,dtm_reproj_file,src_crs,dst_crs)
# Args:
# dtm_file path to location of geotiff of elevation (in WGS84 lat/long)
# dtm_reproj_file path to location of geotiff of elevation (in projection defined by dst_crs)
# src_crs Coordinate Reference System of source geotif (normally WGS 84 lat/long (EPSG:4326))
# dst_crs Coordinate Reference System of destination geotif (any length-based projection)
# 
# Returns rasterio format reprojected of filename dtm_reproj_file of grid of geotif file defined by dtm_file assuming source coordinate reference system (CRS) of src_crs and destination CRS of dsr_crs
############################################
def reproject_dtm(path_in,path_out,src_crs,dst_crs):
    with rasterio.open(path_in) as src:
        transform, width, height = calculate_default_transform(
            src.crs, dst_crs, src.width, src.height, *src.bounds)
        kwargs = src.meta.copy()
        kwargs.update({
            'crs': dst_crs,
            'transform': transform,
            'width': width,
            'height': height
        })


        with rasterio.open(path_out, 'w', **kwargs) as dst:
            for i in range(1, src.count + 1):
                reproject(
                    source=rasterio.band(src, i),
                    destination=rasterio.band(dst, i),
                    src_transform=src.transform,
                    src_crs=src.crs,
                    dst_transform=transform,
                    dst_crs=dst_crs,
                    resampling=Resampling.nearest)
            dst.close()        
    print("reprojected dtm geotif saved as",path_out)

############################################
# get bounds of a dtm
#
# Args:
# path_in path to file rasterio can read
# dst_crs coordinate reference system of raster
# returns:
# bounding box of raster
############################################
def get_dtm_bounds(path_in,dst_crs):            
    with rasterio.open(path_in) as dataset:

        # Read the dataset's valid data mask as a ndarray.
        mask = dataset.dataset_mask()
        for geom, val in rasterio.features.shapes(
                    mask, transform=dataset.transform):

                # Transform shapes from the dataset's own coordinate
                # reference system to 28350.
                geom_rp = rasterio.warp.transform_geom(
                    dataset.crs, dst_crs, geom, precision=6)

                # Print GeoJSON shapes to stdout.
                #print(geom_rp)
                return(geom_rp)

**Comment by AlexanderJuestel** [comment]
Hello @domist07,

I was able to request some elevation data via a WCS server. Unfortunately not via OWSLib but it works....I am still wondering how you got data from a WMS server as they only provide an image of the data. 

Here is the link to a sample notebook: [Link](https://github.com/cgre-aachen/gemgis/blob/dev_aj/notebooks/misc/01_Request_WCS_Elevation_Data_from_Geobasis_NRW.ipynb)
