### ISSUE TITLE
Check link to Google EarthEngine through geemap Project

### ISSUE THREAD

**Issue by flohorovicic** [cgre-aachen/gemgis#61]
**Is your feature request related to a problem? Please describe.**
No - but would potentially be awesome for better links to real-world data (and model publication?)

**Describe the solution you'd like**
Link to EarthEngine through geemap

**Describe alternatives you've considered**
ArcGIS/ QGIS (e.g. cgre-aachen/gemgis#18) - ideally, both aspects will be complementary.

**Additional context**
https://github.com/giswqs/geemap/blob/master/README.rst

**Comment by AlexanderJuestel** [comment]
Will be picked up in #109 again. Closing this here for now
