### ISSUE TITLE
Getting bottom of layer z coordinates after Borehole Extraction 

### ISSUE THREAD

**Issue by saalnafisi** [cgre-aachen/gemgis#68]
Hello 

I followed [this example](https://github.com/cgre-aachen/gemgis/blob/master/notebooks/08_GemGIS_Extracting_Boreholes_and_Depth_Maps.ipynb) to extract the borehole log giving x and y coordinates. Everything is working for me except that I would like to get the values of the bottom layer of each surface and preferably the id for each surface. Is there a way to get that from the solution that was extracted for the borehole log? 

Many thanks for your help in advance.

**Comment by AlexanderJuestel** [comment]
Dear @saalnafisi, 

as mentioned in the other issue, the extraction has been a very basic feature so far. We are more than happy to implement your requested features :)

Cheers Alex

**Comment by AlexanderJuestel** [comment]
Hey, 
I managed to get a first example running with the depths. Let's see how the ID thing goes ;)

![image](https://user-images.githubusercontent.com/45469915/92579804-f13f7600-f28d-11ea-9f0b-2899592bb791.png)

**Comment by saalnafisi** [comment]
Amazing, thanks for your prompt repsonse and hard work. It would be even better if we can have them stored in the class "solution" to be used for post-interpolation processing. A perfect output for my case would be an array or dict with [surface id,bottom_layer_value] sorted by youngest to oldest formation (i.e. order_surfaces). For this gimgis example,  it would be something like [[1,460],[2,400],[3,300]].

Thanks again and keep up the good work.

**Comment by AlexanderJuestel** [comment]
Ah, great idea! I will add that as another return argument ;)

**Comment by AlexanderJuestel** [comment]
Looks good so far :) 

I will test it with the other examples and fix some bugs that may pop up ;) 

![image](https://user-images.githubusercontent.com/45469915/92587970-abd47600-f298-11ea-81a9-3503b3ceae90.png)
