### ISSUE TITLE
ValueError: 'box_aspect' and 'fig_aspect' must be positive  <Figure size 1440x720 with 2 Axes>

### ISSUE THREAD

**Issue by kaki222** [cgre-aachen/gemgis#75]
I get the above error when trying to execute the following
fig, ax1, ax2 = gg.visualization.plot_data(geo_data, 
                           show_geolmap=True, 
                           show_interfaces=True,
                           add_to_extent=300 
                           )
random_points.plot(ax=ax1, color='red')
![image](https://user-images.githubusercontent.com/34009148/97381915-87ce0200-18e3-11eb-9217-f84fdea3314c.png)
I could not understand it. The same happened for the randomlines.
Thanks in advance

**Comment by AlexanderJuestel** [comment]
Hey @kaki222,

This is a bug that will be fixed in the version being released in a few hours. It has to do with geopandas. If you want to plot multiple geodataframes at the same time, you have to add `aspect = 'equal' ` to every plot command.

I will let you when the new version is ready :)

Cheers

**Comment by kaki222** [comment]
Thanks Alexander,
I knew it was a bug but I was reluctant.
Cheers

**Comment by AlexanderJuestel** [comment]
The issue should be solved now with the latest release. Let us know if there are any more issues!
