### ISSUE TITLE
How to construct acurate parametric Geo-Model out of a bunch of pictures (elevation, seismic, porosity-Thickness, etc))

### ISSUE THREAD

**Issue by kaki222** [cgre-aachen/gemgis#79]
I have a number of pictures such as cross-section of the geo-model, gamma-ray log, seismic2D, permebility, porosity-tickness. How could I use GemGIS to kick start the process of recreating the Geo-Model.
Any hint is welcome.
Attached the actual pictures.
Thanks in Advance.
![Elevation](https://user-images.githubusercontent.com/34009148/98433428-8a4d0a80-20e0-11eb-939e-b8ae3951b904.jpg)
![Gamma-Ray](https://user-images.githubusercontent.com/34009148/98433430-8c16ce00-20e0-11eb-86e1-e37b93a27597.jpg)
![Permeability](https://user-images.githubusercontent.com/34009148/98433432-8caf6480-20e0-11eb-8a65-a4c49acd4e3d.jpg)
![Porosity](https://user-images.githubusercontent.com/34009148/98433434-8de09180-20e0-11eb-82b4-caa60f6b5b7e.jpg)
![Porosity-Thickness](https://user-images.githubusercontent.com/34009148/98433436-8e792800-20e0-11eb-96dd-814fe0f5feb8.jpg)
![Resistivity](https://user-images.githubusercontent.com/34009148/98433437-8f11be80-20e0-11eb-9c26-9fda9e8f270a.jpg)
![Seis-2D](https://user-images.githubusercontent.com/34009148/98433438-8faa5500-20e0-11eb-91ee-371dfd7d1ca5.jpg)
![W-E-Cross](https://user-images.githubusercontent.com/34009148/98433439-90db8200-20e0-11eb-8fb2-529e4a250c25.jpg)

**Comment by AlexanderJuestel** [comment]
Hey @kaki222,

Thank you very much for your message. Let's see:

First of all I would recommend georeferencing your section in a GIS environment (Qgis, ArcGIS). You can use the image with your layer isolines. Based on your scale bar, you can chose the right extent in X and Y direction (in meter).

Then, I recommend to digitize your isolines and the two faults that are indicated using a shape file (lines).

Once you have that, let me know and we can continue the model building process.

Cheers Alex

**Comment by kaki222** [comment]
I am sorry, I have struggled with QGIS (ubuntu). Please let me know if that is what you asked for in the first part.

![Elevation22_v01](https://user-images.githubusercontent.com/34009148/98467439-bc4c9280-21ee-11eb-8da1-38c9d46bf893.jpg)

TOP LET CORNER:

UTM Easting : 276185.94
UTM Northing : 4692654.13
UTM Zone : 19T
EPSG:4326 - WGS 84

For the second part I can digitize the contours with points but I don't know to digitize using shape file, Please hint. I am using WebPlotDigitizer, https://apps.automeris.io/wpd/

Thanks in advance.

**Comment by AlexanderJuestel** [comment]
Hey @kaki222, 

have you used QGIS before? If not, have a look at some tutorials maybe. 

So, my advice would be to georeference your raster (https://www.qgistutorials.com/en/docs/georeferencing_basics.html). Then create a new line shape file, add a field called "Z" to it which should be a number and then digitize the contour lines. For each line you can provide the depth as Z value. Here is a little article on how to create a shape file in QGIS (https://freegistutorial.com/how-to-create-a-new-shapefile-in-qgis/). 

Let me know if that helped you or not. Then I will provide further assistance!
Cheers Alex

**Comment by kaki222** [comment]
Dear Alex,
I tired my best. I have geo-referenced the ISOPACK (Boylston, MA). I don't know if it makes much sense as this topo is 5km deep underground, meaning the projection does it still the same as on the earth surface.

Then I created  created two shape files (CONOTURS and FAULTS). Two faults with field RIGHT and LEFT. For the CONTOURS they according to depths. However, i did not know how to store the two contours cut by the faults and the sides are shifted. So, what I did is for example CONTOURS-5100, it has four sections, I digitize one side and input 5100.00001, then the next side with 5100.00002, the third with 5100.00003 and the last side 5100.00004. I don't if it should be done like this.

Also I don't how to export the shape files on its own, I have  the QGZ_Files. Please let me know how to send these files.

Thanks in advance

**Comment by kaki222** [comment]
Dear Alex,
I think, I did it with some accuracy.
[DE-FAULTS_SHP.zip](https://github.com/cgre-aachen/gemgis/files/5509520/DE-FAULTS_SHP.zip)
[DE-CNTRS_SHP.zip](https://github.com/cgre-aachen/gemgis/files/5509521/DE-CNTRS_SHP.zip)
Thanks in advance.

**Comment by AlexanderJuestel** [comment]
Hey, good job!

Now, you can load the data with GeoPandas into a Jupyter Notebook (`gpd.read_file(...)`) and use GemGIS functions to extract the X and Y coordinates from your data that you can then use for the modeling in GemPy.

**Comment by kaki222** [comment]
Hi Alex,
I get 
AttributeError: 'NoneType' object has no attribute 'plot'

Please note I made it work before this error.
Thanks
#########################################################
import sys
sys.path.append('../../gemgis')

import gemgis as gg
import geopandas as gpd
import rasterio
import numpy as np
import matplotlib.pyplot as plt

import gempy as gp
from matplotlib.colors import ListedColormap
print(gp)
print(gp.__version__)

geo_data = gg.GemPyData(model_name='Model1', 
                        crs='EPSG:32619', 
                        extent=[0., 10000., 0., 10000., 4000., 6000.], 
                        resolution=[500,500,500],
                        stack={"Strat_Series": ('Sand', 'Ton')},
                        dem='../data/alcocer/boylston_raster.tif',
                        surface_colors= {'Ton':'#015482',
                                         'Sand':'#9f0052',
                                         'basement':'#ffbe00'})

topo = gpd.read_file('../data/alcocer/DE-CNTRS_SHP/DE-CNTRS_SHP.shp')
geological_map = rasterio.open('../data/alcocer/boylston_raster.tif')

{i: dtype for i, dtype in zip(geological_map.indexes, geological_map.dtypes)}
{1: 'uint16'}

geo_data.raw_dem = topo
#geo_data.raw_demF = fault
geo_data.raw_dem.head()

geological_map.bounds

#geo_data.raw_dem.crs

gg.visualization.plot_data(geo_data, 
                           show_geolmap= True, 
                           show_topo=True,
                           )

#####################################


[dt.zip](https://github.com/cgre-aachen/gemgis/files/5517232/dt.zip)

**Comment by kaki222** [comment]
Hi,
The mistake I did is in:
dem='../data/alcocer/boylston_raster.tif' 
not the right raster. but it did not complaint when executing 
geo_data = gg.GemPyData(model_name='Model1',...

It complained when executing 
gg.visualization.plot_data(geo_data, ...

Thank you anyway. 
I think I need to close this issue.
