### ISSUE TITLE
How to honor the zenith point (top elevation) 

### ISSUE THREAD

**Issue by kaki222** [cgre-aachen/gemgis#81]
Dear GemPy Forum
I have almost fitted the surface using a good number of data but only, the surface stops at the upper most contour without closing. 
How can I close the surface by honoring the top elevation point (X_top, Y_top, Z_top)=Last point in CONTOUR-40.csv (I know it does not belong to this contour in fact Z_top=49').

Also looking a the origin of my data (SPE paper). It is an isopach attached.
<img width="448" alt="ISOPACH" src="https://user-images.githubusercontent.com/34009148/97080736-b9f31180-160e-11eb-8465-f9f5537c7534.png">

is it fair to think of just a flat basement?
I attach the code (Adaptation of Dr. Miguel) and data (webdigitizer: extracted four contours, East-West Line and North-South Line and the Wells Positions). Any advise and code improvement are welcome.

By the way I am very new to GemPy. (Coming from ISDX Creo, formerly ProEngineer).

Thank you in advance. 

[Code.docx](https://github.com/cgre-aachen/gempy/files/5432808/Code.docx)
![Forum-Q2-PIC](https://user-images.githubusercontent.com/34009148/97080658-1570cf80-160e-11eb-83e6-1c8e75580f0b.jpg)
[data.zip](https://github.com/cgre-aachen/gempy/files/5432809/data.zip)

**Comment by AlexanderJuestel** [comment]
Hello @kaki222, 

the feature is available in GemGIS now. Are you still working on your model?

**Comment by AlexanderJuestel** [comment]
Closed due to inactivity

**Comment by kaki222** [comment]
Thanks for asking
I moved away from this for now.
I hope I will see you on 19th of April 2021

https://meetingorganizer.copernicus.org/EGU21/session/38927

Regards
Kaki222
