### ISSUE TITLE
Create 2D cross section

### ISSUE THREAD

**Issue by kashkoulimohammad** [cgre-aachen/gemgis#82]
Dear all,
I would like to create the attached file.
Can anyone help me?

Regards,
Mohammad
![2d_cross section](https://user-images.githubusercontent.com/11463583/87975769-532afd00-cae1-11ea-9e39-fe1b6ed2050d.png)

**Comment by AlexanderJuestel** [comment]
Will be closed due to inactivity. Feel free to reopen it if needed.
