### ISSUE TITLE
Creating a 3D velocity model in GemPy

### ISSUE THREAD

**Issue by adleram** [cgre-aachen/gemgis#83]
Hi All,

Started recently to work with GemPy, targeting automatic generation of realistic 3D velocity models. So far, I have not found a simple way to perform this, and wondered if anyone has accomplished this before, or saw sample code that performs this? 

Best,

Amir

**Comment by AlexanderJuestel** [comment]
By combining this with density, even a simple synthetic seismic section or cube could be calculated.

**Comment by AlexanderJuestel** [comment]
Closing because of duplicate of #64
